### ISSUE TITLE
relion reweighting script

### ISSUE THREAD

**Issue by azazellochg** [leschzinerlab/Relion#1]
Hello @mcianfrocco ,
I've got a problem running your reweight_particle_stack.py script. It does not seems to remove particles within specified angular range but rather randomly (?). I ran 
`reweight_particle_stack.py --stareuler=sub_low_subtracted.star --starparticle=sub_low_subtracted.star --remove=23000 --AngleRotLim1=150 --AngleRotLim2=180 --saveremoved` and got removed 23000 particles as requested, however the distribution plot didn't change. Also, if I compare number of the particles before and after:
`awk 'NF>3&&$19>=150&&$19<=180{print $19}' sub_low_subtracted.star | wc`  gives 35556
`awk 'NF>3&&$19>=150&&$19<=180{print $19}' sub_low_subtracted_reweight.star  | wc`  gives 27795

this is clearly not a 23000 difference.. any ideas?

PS. actually, what is the difference btw --starparticle and --stareuler params? they seem to be the same thing

**Comment by ketica** [comment]
Helo.

I encountered the sample problem when running the same reweight_particle_stack.py script as you describe here - no change in angular distribution plot even though it removes specified number of particles. However it also removed rather randomly.

Did you manage to solve this issue in the end?

**Comment by azazellochg** [comment]
Hi, @ketica,

I think I had to write my own : https://github.com/azazellochg/Relion/blob/master/remove_pref_views.sh
This was few years ago so you will have to check it yourself

**Comment by ketica** [comment]
Hi,  @azazellochg ,

Everything works, thanks a lot for help!

**Comment by longhuali** [comment]
Hi, @azazellochg ,
I can only remove some particles per time only in one kind of angle, see Rot. But it is globular. If I try to remove some preferred particles specifically, I should input all three angles, at least two angles. Could you give me any suggestion? Thanks!

**Comment by azazellochg** [comment]
Hi @longhuali , I haven't used my script for years. What you are trying to do is supposed to be done by the original reweight_particle_stack.py script. If you can figure out what's wrong with it :)

**Comment by azazellochg** [comment]
I guess you could run my script 2 or 3 times so only particles within range for 2-3 angles left. Then just remove them from the original star file.

**Comment by longhuali** [comment]
Hi azazellochg, thanks!
